app = "signal-rag-data"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  OPENAI_EMBEDDING_MODEL = "text-embedding-3-large"
  CHROMA_COLLECTION_NAME = "signal_knowledge"
  CHROMA_HOST = "signal-rag-chroma.internal"
  CHROMA_PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[processes]
  app = "npm run setup"

[scale]
  min_machines = 1
  max_machines = 1